services:
  serena:
    image: kojeomstudio/serena:prod-v1
    # To work with projects, you must mount them as volumes:
    restart: unless-stopped
    volumes:
      # - ./my-project:/workspace/my-project
      - /Users/kojeomstudio/:/target_projects/
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - "${SERENA_PORT:-9121}:9121"  # MCP server port
      - "${SERENA_DASHBOARD_PORT:-24282}:24282"  # Dashboard port (default 0x5EDA = 24282)
    environment:
      - SERENA_DOCKER=1
    command:
      - "uv run --directory /target_projects serena-mcp-server --transport sse --port 9121 --host 0.0.0.0 --context ide-assistant"
      # Add the context for the IDE assistant
      # - "uv run --directory . serena-mcp-server --transport sse --port 9121 --host 0.0.0.0 --context ide-assistant"

  serena-win64:
    image: kojeomstudio/serena:prod-win64-v1
    # To work with projects, you must mount them as volumes:
    restart: unless-stopped
    volumes:
      # - ./my-project:/workspace/my-project
      - C:/Workspaces/l1server:/serena_projects
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - "${SERENA_PORT:-9121}:9121"  # MCP server port
      - "${SERENA_DASHBOARD_PORT:-24282}:24282"  # Dashboard port (default 0x5EDA = 24282)
    environment:
      - SERENA_DOCKER=1
    command:
      - "uv run --directory /serena_projects serena-mcp-server --transport sse --port 9121 --host 0.0.0.0"
      # Add the context for the IDE assistant
      # - "uv run --directory . serena-mcp-server --transport sse --port 9121 --host 0.0.0.0 --context ide-assistant"
  serena-dev:
    image: kojeomstudio/serena:dev-v1
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - SERENA_DOCKER=1
    volumes:
      - .:/workspaces/serena
    ports:
      - "${SERENA_PORT:-9121}:9121"  # MCP server port
      - "${SERENA_DASHBOARD_PORT:-24282}:24282"  # Dashboard port
    command:
      - "uv run --directory . serena-mcp-server --transport sse --port 9121 --host 0.0.0.0"
